set = RV32V
width = 32

[types]
names = [
    "format_1",
    "format_2",
    "format_3",
    "format_4",
    "format_5",
    "format_6",
    "format_7",
    "format_8",
    "format_9",
    "format_10",
    "format_11",
    "format_12",
    "format_13",
    "format_14",
    "format_15",
    "format_16",
    "format_17",
    "format_18",
    "format_19",
    "format_20",
    "format_21",
    "format_22",
    "format_23",
    "format_24",
]
parts = [
    [
        "vm",
        1,
        "Register_vm",
    ],
    [
        "vs2",
        5,
        "Register_vec",
    ],
    [
        "vs1",
        5,
        "Register_vec",
    ],
    [
        "vd",
        5,
        "Register_vec",
    ],
    [
        "rs1",
        5,
        "Register_int",
    ],
    [
        "simm5",
        5,
        "VInt",
    ],
    [
        "rd",
        5,
        "Register_int",
    ],
    [
        "nf",
        3,
        "u8",
    ],
    [
        "rs2",
        5,
        "Register_int",
    ],
    [
        "vs3",
        5,
        "Register_vec",
    ],
    [
        "zimm10",
        10,
        "VInt",
    ],
    [
        "zimm",
        5,
        "VInt",
    ],
    [
        "zimm11",
        11,
        "VInt",
    ],
    [
        "none",
        32,
        "u32",
    ]
]

[type]
names = ["type_1", "type_2", "type_3", "type_4", "type_5", "type_6", "type_7", "type_8", "type_9", "type_10", "type_11", "type_12", "type_13", "type_14", "type_15", "type_16", "type_17", "type_18", "type_19", "type_20", "type_21", "type_22", "type_23", "type_24"]
type_1 = [
    { name = "none", top = 31, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "vs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_2 = [
    { name = "none", top = 31, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_3 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "simm5", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_4 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "vs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_5 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_6 = [
    { name = "none", top = 31, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "simm5", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_7 = [
    { name = "none", top = 31, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "none", top = 19, bot = 12 },
    { name = "rd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_8 = [
    { name = "none", top = 31, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "none", top = 19, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_9 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "none", top = 19, bot = 12 },
    { name = "rd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_10 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_11 = [
    { name = "none", top = 31, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "none", top = 24, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_12 = [
    { name = "nf", top = 2, bot = 0 },
    { name = "none", top = 28, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "none", top = 24, bot = 20 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_13 = [
    { name = "nf", top = 2, bot = 0 },
    { name = "none", top = 28, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_14 = [
    { name = "nf", top = 2, bot = 0 },
    { name = "none", top = 28, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "rs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_15 = [
    { name = "none", top = 31, bot = 25 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "none", top = 19, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_16 = [
    { name = "none", top = 31, bot = 20 },
    { name = "simm5", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_17 = [
    { name = "none", top = 31, bot = 20 },
    { name = "vs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_18 = [
    { name = "none", top = 31, bot = 20 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vs3", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_19 = [
    { name = "nf", top = 2, bot = 0 },
    { name = "none", top = 28, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "none", top = 24, bot = 20 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vs3", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_20 = [
    { name = "none", top = 31, bot = 30 },
    { name = "zimm10", top = 9, bot = 0 },
    { name = "zimm", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_21 = [
    { name = "none", top = 31, bot = 25 },
    { name = "rs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_22 = [
    { name = "none", top = 31, bot = 31 },
    { name = "zimm11", top = 10, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "rd", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_23 = [
    { name = "nf", top = 2, bot = 0 },
    { name = "none", top = 28, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "vs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vs3", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]
type_24 = [
    { name = "nf", top = 2, bot = 0 },
    { name = "none", top = 28, bot = 26 },
    { name = "vm", top = 0, bot = 0 },
    { name = "rs2", top = 4, bot = 0 },
    { name = "rs1", top = 4, bot = 0 },
    { name = "none", top = 14, bot = 12 },
    { name = "vs3", top = 4, bot = 0 },
    { name = "none", top = 6, bot = 0 },
]

[format_1]
type = "type_1"
[format_1.repr]
